server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: tenant-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888