server:
  port: 8080

spring:
  application:
    name: attachment-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:prolance-attachment}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    region: ${AWS_REGION:eu-north-1}
