server:
  port: 8080

spring:
  application:
    name: project-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: project-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"